### ISSUE TITLE
Auth PA Review

### ISSUE THREAD

**Issue by ldtcooper** [ldtcooper/alchemy-chart#7]
PA review for user authentication

**Comment by chungkikelly** [comment]
1. Can't currently sign up using the username / password: chungkikelly / password
2. Throws Uncaught Error: Given action "RECEIVE_ERRORS", reducer "session" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
3. On log out - username / password for log in form doesn’t clear

**Comment by ldtcooper** [comment]
Took out debugger in users controller that was stopping signup process. Auth should be working now.
